apiVersion: v1
kind: ReplicationController
metadata:
  name: new-urwish-rc
spec:
  replicas: 4
  template:
    metadata:
      name: new-pod
      labels:
        env: dev
    spec:
      containers:
      - image: nginx
        name: nginxurwish
